services:
  db:
    image: postgres:16
    container_name: csgo_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro

  app:
    build:
      context: ./app
    container_name: csgo_app
    depends_on:
      - db
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    # Держим контейнер живым; команды выполняй через `docker compose exec app ...`
    command: ["sleep","infinity"]
    volumes:
      - logs:/logs

volumes:
  db_data:
  logs:
