services:
  db:
    build: ./db
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--locale=ru_RU.UTF-8 --encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: pg_client
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["python","app.py"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: {}

