-- 03_grants.sql
SET search_path TO csgo, public;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='app_user') THEN CREATE ROLE app_user LOGIN PASSWORD 'app_pass'; END IF; END $$;
GRANT USAGE ON SCHEMA csgo TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA csgo TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA csgo TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA csgo GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA csgo GRANT USAGE, SELECT ON SEQUENCES TO app_user;